spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: recipeapi
          uri: http://localhost:8080
          predicates:
            - Path=/api/recipes/**
        - id: userservice
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/**

server:
  port: 8079